"""Copy brand-safe notes into the brand repo's knowledge folder (gate 2 lives here).

Only title, date, tags, lessons and post angle leave the vault. Project, cwd and the
work log never do. A note whose exported text matches the NDA denylist (vault file plus
the brand's own `nda-*` regex rules) is dropped. A bad pattern stops the export.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional, Pattern

from . import gitsync, note
from .config import Config

INDEX = "INDEX.md"
INDEX_LIMIT = 200


class ExportError(Exception):
    pass


@dataclass
class Result:
    exported: List[str] = field(default_factory=list)
    blocked: List[str] = field(default_factory=list)
    committed: bool = False


def _compile(pattern: str, source: str) -> Pattern:
    try:
        return re.compile(pattern, re.IGNORECASE)
    except re.error as exc:
        raise ExportError(f"bad pattern in {source}: {pattern!r} ({exc})") from exc


def denylist(cfg: Config) -> List[Pattern]:
    patterns = []
    if cfg.denylist.exists():
        for line in cfg.denylist.read_text(encoding="utf-8").splitlines():
            if line.strip() and not line.lstrip().startswith("#"):
                patterns.append(_compile(line.strip(), str(cfg.denylist)))
    rules_file = cfg.export_repo / cfg.export_rules if cfg.export_repo else None
    if rules_file and rules_file.exists():
        for rule in json.loads(rules_file.read_text(encoding="utf-8")).get("rules", []):
            if rule.get("kind") == "regex" and str(rule.get("category", "")).startswith("nda"):
                patterns += [_compile(p, f"{rules_file}:{rule.get('id')}") for p in rule.get("patterns", [])]
    return patterns


def _knowledge_note(meta: dict, lessons: str, angle: str) -> str:
    head = {"title": meta.get("title", ""), "date": str(meta.get("date", "")), "tags": meta.get("tags", [])}
    lines = "\n".join(f"{k}: {json.dumps(v, ensure_ascii=False)}" for k, v in head.items())
    return (f"---\n{lines}\n---\n# {head['title']}\n\n## Cerita (post angle)\n{angle}\n\n"
            f"## Pelajaran\n{lessons}\n")


def _index(entries: List[tuple]) -> str:
    rows = [f"- {date} [{title}]({name})" for date, name, title in entries[:INDEX_LIMIT]]
    return ("# Knowledge index\n\nReal work stories from Adyan's own projects, newest first. "
            "Generated by session-journal; do not edit.\n\n" + "\n".join(rows) + "\n")


def collect(cfg: Config, deny: List[Pattern]) -> tuple:
    files, entries, result = {}, [], Result()
    for path in sorted((cfg.vault / "sessions").rglob("*.md"), reverse=True):
        meta, body = note.split(path.read_text(encoding="utf-8"))
        angle = note.section(body, "Post angle")
        if meta.get("brand_safe") is not True or not angle:
            continue
        lessons = note.section(body, "Lessons")
        text = f"{meta.get('title', '')}\n{lessons}\n{angle}"
        if any(p.search(text) for p in deny):
            result.blocked.append(path.name)
            continue
        files[path.name] = _knowledge_note(meta, lessons, angle)
        entries.append((str(meta.get("date", "")), path.name, meta.get("title", path.stem)))
        result.exported.append(path.name)
    entries.sort(reverse=True)
    return files, entries, result


def run(cfg: Config) -> Optional[Result]:
    if not cfg.export_repo:
        return None
    if not (cfg.export_repo / ".git").exists():
        raise ExportError(f"export repo {cfg.export_repo} is not a git clone; see SKILL.md setup")
    with gitsync.repo_lock(cfg.export_repo, cfg.state_dir):
        if gitsync._has_remote(cfg.export_repo):
            gitsync._pull(cfg.export_repo)
    deny = denylist(cfg)
    files, entries, result = collect(cfg, deny)
    out_dir = cfg.export_repo / cfg.export_dir
    wanted = {f"{cfg.export_dir}/{name}": text for name, text in files.items()}
    wanted[f"{cfg.export_dir}/{INDEX}"] = _index(entries)
    stale = [f"{cfg.export_dir}/{p.name}" for p in out_dir.glob("*.md")
             if f"{cfg.export_dir}/{p.name}" not in wanted] if out_dir.exists() else []
    result.exported.sort()
    result.committed = gitsync.sync_write(cfg.export_repo, wanted, "knowledge: sync from session-journal",
                                          cfg.state_dir, deletes=stale)
    return result
